const LOREM = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'

const SC = 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/soundcloud%253Atracks%253A2271615800&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true'

export const interviews = [
  {
    id: 'jesse',
    names: ['Jesse Hawthorne Ficks'],
    thumbs: ['thumb_Jesse.png'],
    location: 'Stranded Records',
    tagline: 'Film history teacher whose had his first record, a Beastie Boys 7-inch, since the day he bought it.',
    mediaType: 'text',
    embedUrl: null,
    paragraphs: [
      "Jesse Hawthorne Ficks sits behind the counter of Stranded Records, greeting customers as they walk through the door. It's another Record Store Day, and die-hard collectors across the country are hitting up their local store to look for any gems.",
      "Among those hoping to strike gold on this year's Record Store Day is Ficks's 82-year-old father.",
      '"He\'s pretty old," Ficks said. "He\'s still doing it."',
      "That passion and love for vinyl, the same one that keeps the 82-year-old going, can be seen in Ficks and the way he talks about records.",
      "Ficks's father introduced him to vinyl records at a young age. But those first records were his parents', and Ficks wanted to start his own collection.",
      "So he went to a store and bought his first record ever — a seven-inch of the Beastie Boys. He compared the feeling of buying to that of getting your first pet.",
      '"It\'s only yours, it\'s not a hand me down," Ficks said, adding that he still feels that way with each record he still buys. "It solves all the problems in the world."',
      "Ficks, now a film history teacher, still owns that Beastie Boys record to this day. It's now just one of a plethora of records he now owns, placing mementos and other meaningful keepsakes, creating a musical time capsule.",
      '"You know, that scene in Interstellar?" Ficks asked. "I look at my record collection that way, that it\'s just all the moments, in that year, in that month, with that person."',
      "Drawing on the literary concept of realism, Ficks, who described himself as straddling between physical and digital media, suggests the term can also be applied to vinyl.",
      '"When you cook food, whatever emotions you have, supposedly people can taste that in the food," Ficks said. "I think that might be the case with a record — any person that\'s had it before, I\'m part of that process. If it\'s new, it\'s only lived with me, therefore it\'s all my emotions only."',
    ],
  },
  {
    id: 'castillo',
    names: ['Jason', 'Ruben Castillo'],
    thumbs: ['thumb_Jason.png', 'thumb_Ruben.png'],
    location: 'San Francisco',
    tagline: 'Father and son approaching the crates like an art form — quick, intentional, and in search of the undiscoverable.',
    mediaType: 'text',
    embedUrl: null,
    paragraphs: [
      "Jason Castillo's nimble fingers quickly flip through the shelves at Stranded Records, searching for fresh new sounds for an upcoming set. His son, Ruben, follows, looking for lost media that never made it onto streaming.",
      '"I\'ve learned to stray away from stuff I can stream so easily," Ruben said. "It\'s now about discovering stuff."',
      "Castillo started collecting records in the early 90s. Searching for small releases from the past to unknown records from a global scale, Castillo approaches the bins like an art form that can't be replicated.",
      "Quick, yet intentional. Because that's what vinyl should be, Castillo and Ruben said.",
      { type: 'image', src: 'photo_jason&ruben.jpg', alt: 'Jason and Ruben Castillo' },
      '"Everything about vinyl is intentional," Castillo said. "If it\'s digital, it tends to be passive. You\'re in your car, or you\'re walking somewhere. You have to want to listen to something physical."',
      "Castillo, who is an archivist and owns a record label, believes vinyl records are one of the few examples of media built to withstand the test of time.",
      "Even with digital streaming being the norm, there's a feeling that can only be obtained by unearthing rare and obscure records that can't be found anywhere else.",
      '"Young adults tend to approach vinyl like a trophy as if it\'s an investment or a cool thing to have," Castillo said. "I think they\'re missing out on what it\'s made for in the first place. Music\'s made to be played, not kept in the shrink wrap and put up on a shelf like a trophy or a deer head."',
    ],
  },
  {
    id: 'jon',
    names: ['Jon Blunck'],
    thumbs: ['thumb_Jon.png'],
    location: "Rooky Ricardo's",
    tagline: 'A man who has owned over 20,000 records and never once used a streaming service.',
    mediaType: 'text',
    embedUrl: null,
    paragraphs: [
      "Having never used a music streaming service, Jon Blunck is a rarity in today's world.",
      "Blunck sits behind the counter at Rooky Ricardo's on Record Store Day. Thousands of vinyl records make up the cramped little space, where beloved owner Dick can be overheard recommending his extensive knowledge of women's bands to his favorite customers.",
      "It's a record junkie's paradise, and what better place to be for someone like Blunck, who has owned more than 20,000 records in his lifetime.",
      '"It\'s very addictive once you start buying records," Blunck said. "There\'s something about holding a record and owning it."',
      "Vinyl has been Blunck's medium for as long as he can remember. The tactile experience of gently ripping apart the clear shrink wrap off a new album and the act of studying the written texts inside translates to preservation for him.",
      '"If you notice on LPs there is a cover you can look at, and then on the back you can read inserts that have lyrics," Blunck said. "You can sit there, read, and it\'s all beautiful. I\'ve been doing it my whole life."',
      "Today, Blunck owns just one record, an album made by a late friend. During the pandemic, Blunck needed to sell his records to survive. He said it took him just a year to go through his extensive catalog. Once he did, he opened up a store in Sacramento and never looked back.",
      '"I don\'t regret selling them," Blunck said. "The important ones will always be inside my heart."',
      { type: 'image', src: 'photos_jon_album.jpg', alt: 'Description of photo' }
    ],
  },
  {
    id: 'john',
    names: ['John McCord'],
    thumbs: ['thumb_John.png'],
    location: 'Down Home Music',
    tagline: '40 years preserving the spirit of vernacular music at Down Home Music in El Cerrito.',
    mediaType: 'audio',
    embedUrl: SC,
    paragraphs: [
      'For the last 40 years, John McCord has been trying to "keep the spirit of vernacular music" alive through his work at Down Home Music in El Cerrito.',
      "McCord, who grew up in the East Bay, was first introduced to vinyl records through a jukebox at a bar owned by his Uncle Barry in San Leandro. When his uncle got a new jukebox that played 45s, he gave the old one that played 78s to McCord.",
      "Inside was a trove of popular music from Elvis to Fats Domino, McCord recalls. Those 78s, McCord says, contained real American life, experiences from fields and bar rooms across the country.",
      '"The act of dropping the needle and then listening to the records is an act of reverence," McCord said. "And you can brag about finding it long ago; a favorite thing or totally obscure band that you all of a sudden fall in love with because you hear it, and it\'s more uplifting than going online."',
      "Overlooking the Santa Barbara coast during the summer of 1967, McCord sparked up with a few friends and listened to a newly released Beatles album — Sgt. Pepper's Lonely Hearts Club Band. The album would change the way the world saw rock as an art form.",
      "But for the moment, the group enjoyed a feeling that McCord says streaming and CDs don't quite evoke: community.",
      '"An LP really demonstrates the impact of the music in a way that it\'s something you can pass around and everybody can look at and appreciate," McCord said. "It has a social aspect that other forums don\'t quite (have), you know?"',
    ],
  },
  {
    id: 'gabriel',
    names: ['Gabriel Dela Cruz'],
    thumbs: ['thumb_Gabriel.png'],
    location: 'Hayward',
    tagline: "DJ, educator and owner of The Stacks Record Shop in Hayward.",
    mediaType: 'video',
    embedUrl: 'https://www.youtube.com/embed/hieuJsbRkVo',
    paragraphs: [
      "MF Doom, Run DMC, John Coltrane. Those are just a few of the legendary artists hanging on the walls of The Stacks Record Shop in Hayward.",
      "Dela Cruz started digging heavily through crates filled with vinyl records at his local shop in Pleasant Hill as a teenager in the early 2000s. Having gotten his first pair of turntables around that time, he'd cut school to try and get the latest record.",
      "His collection eventually got so large that he decided to open up his own record store.",
      '"It\'s a modest collection, like somewhere over 1,000 some people," Dela Cruz said. "But I think for some of us, people who like, dig, it\'s \'1,000 records? That\'s nothing\'. Come see my storage unit. I got 10,000."',
      "Dela Cruz, who today spins tables under the alias Mighty DJ DelRokz, believes vinyl's longevity in a growing digital age and its resurgence can be attributed to how close-knit the community is.",
      "He says record collectors and stores need each other to survive. Dela Cruz also gave Dick Vivian, the owner of Rooky Ricardo's, his flower, saying many record stores in San Francisco wouldn't exist without him or his guidance.",
      '"We\'re all here to support each other," Dela Cruz said. "It\'s all love, it\'s not competition. There are records for everyone."',
    ],
  },
  {
    id: 'carolyn',
    names: ['Carolyn Wysinger'],
    thumbs: ['thumb_Carolyn.png'],
    location: 'El Cerrito',
    tagline: "El Cerrito City Councilmember who once found what may have been her own aunt's 1950s gospel record in a crate.",
    mediaType: 'audio',
    embedUrl: SC,
    paragraphs: [LOREM],
  },
  {
    id: 'erika',
    names: ['Erika Royo'],
    thumbs: ['thumb_Erika.png'],
    location: 'San Bruno',
    tagline: 'Digging through bins at the Alameda Record Swap for some gems to give her teenage son.',
    mediaType: 'video',
    embedUrl: 'https://www.youtube.com/embed/AINAvoGpbc4',
    paragraphs: [LOREM],
  },
  {
    id: 'leo',
    names: ['Leo Rivera'],
    thumbs: ['thumb_Leo.png'],
    location: 'Antioch',
    tagline: 'Record vendor from Antioch searching for sounds worth passing down.',
    mediaType: 'video',
    embedUrl: 'https://www.youtube.com/embed/nWkBLykSgj4',
    paragraphs: [LOREM],
  },
  {
    id: 'molly-trippy',
    names: ['Molly', 'Trippy'],
    thumbs: ['thumb_Molly.png', 'thumb_Trippy.png'],
    location: 'The Mission',
    tagline: 'Mission-based collectors who spin records too rare for an algorithm to find.',
    mediaType: 'audio',
    embedUrl: SC,
    paragraphs: [LOREM],
  },
  {
    id: 'rick',
    names: ['Rick Orbeta'],
    thumbs: ['thumb_Rick.png'],
    location: 'Oakland',
    tagline: 'Collector drawn to all types of music, fron classic hip-hop to Filipino punk and pre-Marcos folk music.',
    mediaType: 'video',
    embedUrl: 'https://www.youtube.com/embed/210YcswIzIA',
    paragraphs: [LOREM],
  },
]
